force-app/main/default/objects/Billing_Rule__c/Billing_Rule__c.object-meta.xml
<CustomObject>
    <label>Billing Rule</label>
    <nameField>
        <label>Billing Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task__c/fields/Billing_Rule__c.field-meta.xml
<CustomField>
    <fullName>Billing_Rule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Rule</label>
    <referenceTo>Billing_Rule__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Time__c/Time__c.object-meta.xml
<CustomObject>
    <label>Time</label>
    <nameField>
        <displayFormat>Time-{0000}</displayFormat>
        <label>Time Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Times</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Time__c/fields/Billing_Rule__c.field-meta.xml
<CustomField>
    <fullName>Billing_Rule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Rule</label>
    <referenceTo>Billing_Rule__c</referenceTo>
    <relationshipLabel>Times</relationshipLabel>
    <relationshipName>Times</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Time__c/fields/Task__c.field-meta.xml
<CustomField>
    <fullName>Task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Task</label>
    <referenceTo>Task__c</referenceTo>
    <relationshipLabel>Times</relationshipLabel>
    <relationshipName>Times</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TableRow.cls
public with sharing class TableRow {
    private Task__c task;
    private Billing_Rule__c billingRule;
    private Integer rowNumber;
    private Map<Date, Time__c> dateToTimeSpend= new Map<Date, Time__c>();

    public TableRow(Task__c task, Billing_Rule__c billingRule, List<Time__c> times, Integer rowNumber, Date startOfWeek){
        this.task = task;
        this.billingRule = billingRule;
        this.rowNumber = rowNumber;
        fillTimeSpendToDayColumn(startOfWeek);
        if(times != null){
            setExistingTimesToColumn(times);
        }
    }

    public List<Time__c> getTimeSpendsCol(){
        return this.dateToTimeSpend.values();
    }

    public Task__c getTask(){
        return this.task;
    }
    
    public Billing_Rule__c getBillingRule(){
        return this.billingRule;
    }
    
    public Integer getRowNumber(){
        return this.rowNumber;
    }

    private void fillTimeSpendToDayColumn(Date startOfWeek){
        for(Integer i =0; i<7; i++){
            Date currentDate = startOfWeek.addDays(i);
            this.dateToTimeSpend.put(currentDate, new Time__c(Date__c = currentDate));
        }
    }

    private void setExistingTimesToColumn(List<Time__c> times){
        for(Time__c tm : times){
            this.dateToTimeSpend.put(tm.Date__c, tm);
        }
    }
}